#**创建PVC资源对象**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany    #这里的访问模式必须与PV资源一致
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs    #存储类的名字，必须与PV资源一致