version: '3'

volumes:
  kuboard-data:
  kuboard-spray-data:

services:
  kuboard:
    image: eipwork/kuboard:v3
    restart: always
    volumes:
      - kuboard-data:/data
    ports:
      - 10080:80/tcp
      - 10081:10081/tcp
    environment:
      - KUBOARD_ENDPOINT="http://192.168.107.119:10080"

  kuboard-spray:
    image: eipwork/kuboard-spray:latest-arm64
    restart: always
    volumes:
      - kuboard-spray-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10083:80/tcp
    environment:
      - KUBOARD_ENDPOINT="http://192.168.107.119:10080"
      - TZ=Asia/Shanghai
# -e KUBOARD_ENDPOINT="http://内网IP:80" \
#   -e KUBOARD_AGENT_SERVER_TCP_PORT="10081" \