apiVersion: v1
kind: Service
metadata:
  labels:
    app: gogs
  name: gogs
  namespace: gogs
spec:
  selector:
    app: gogs
  type: NodePort
  ports:
    - name: gogs
      port: 3000
      targetPort: 3000
      nodePort: 30020