apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gogs
  name: gogs
  namespace: gogs

spec:
  selector:
    matchLabels:
      app: gogs
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
    spec:
      volumes:
        - name: gogs-data
          persistentVolumeClaim:
            claimName: gogs
        - name: config-volume
          configMap:
            name: gogs-config
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
          image: gogs/gogs:latest
          imagePullPolicy: IfNotPresent
          name: gogs
          volumeMounts:
            - name: gogs-data
              mountPath: /data
            - name: config-volume
              mountPath: /data/gogs/conf



