apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs
  namespace: gogs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi

