apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy-app
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-deploy-app
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "deployments" ]
    verbs: [ "get","list","patch","update", "create", "delete" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-deploy-app
  namespace: default
subjects:
  - kind: ServiceAccount
    name: drone-deploy-app
    namespace: default
roleRef:
  kind: Role
  name: drone-deploy-app
  apiGroup: rbac.authorization.k8s.io