network:
  ethernets:
    enp0s5:
      dhcp4: no
      addresses:
        - 192.168.80.31/24
      routes:
        - to: default
          via: 192.168.80.1
      nameservers:
        addresses:
          - 114.114.114.114
          - 202.96.134.133
  version: 2