apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: drone-server-service
spec:
  selector:
    app: drone
    type: server
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30021