kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: bitnami/rabbitmq:3.10.20
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_USERNAME
              value: root
            - name: RABBITMQ_PASSWORD
              value: "123456"
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbit consumer_timeout 36000000"
          ports:
            - containerPort: 15672
              name: rabbit15672
              protocol: TCP
            - containerPort: 5672
              name: rabbit5672
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-pvc
              mountPath: /data/db
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: rabbitmq-pvc
          persistentVolumeClaim:
            claimName: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: rabbit15672
      nodePort: 30364
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: rabbit5672
      nodePort: 30363
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq

