global:
  storageClass: "nfs-client"
architecture: standalone
auth:
  rootPassword: "root"
#  database: "digitization_dev"

image:
  debug: true
  tag: 5.7.42
primary:
  name: primary
  service:
    type: NodePort
    nodePorts:
      mysql: "30362"
