apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client